apiVersion: v1
kind: PersistentVolume
metadata:
  name: secondhand-postgres-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /srv/secondhand/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - osiris
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: secondhand-postgres-pvc
  namespace: secondhand
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: secondhand-postgres-pv
  resources:
    requests:
      storage: 5Gi
